# TODO:
# 1. highlight selected section similar to tabbed sections 
# 2. small caps / breadcrumb styling for headings
site_name: Glean
theme:
  name: material
  palette:
    scheme: glean
  logo: assets/glean-logo-white.png
  favicon: assets/glean-logo.png
  custom_dir: overrides
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.tabs
extra:
  analytics:
    provider: segment
    property: 'YOUR_SEGMENT_KEY'
    api_key: !ENV SEGMENT_KEY
  generator: false
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - footnotes
extra_css:
  - assets/stylesheets/extra.css
nav:
  - Home: index.md
  - Guides:
    - Quickstart: guides/quickstart/index.md
    - Create retention curves: guides/create-retention-curves/index.md
    - Data Modeling Best Practices: guides/data-modeling-best-practices.md
  - Reference: 
    - Glean:
      - Overview: reference/index.md
    - Data Explorer:
      - reference/visualizing-data/Attributes-Tray.md
      - reference/visualizing-data/Breakout.md
      - reference/visualizing-data/Calculations.md
      - reference/visualizing-data/Chart-Interactions.md
      - reference/visualizing-data/Chart-Menu.md
      - reference/visualizing-data/Dashboards.md
      - reference/visualizing-data/Filter.md
    - Data Models:
      - Overview: reference/data-modeling/Data-Models-Overview.md
      - Add a Data Model: reference/data-modeling/add-data-model.md
      - Calculating Metrics: reference/data-modeling/Metrics.md
    - Data Ops:
      - Overview: reference/data-ops/index.md
      - reference/data-ops/Creating-Data-Ops-Builds.md
      - reference/data-ops/Using-the-Glean-CLI.md
      - reference/data-ops/DataOps-Configuration-Schema.md
    - People:
      - Users and Permissions: reference/users-and-permissions.md
    - Settings: 
      - Database Connections: reference/database-connections.md
  - Get in Touch: contact-us.md
