# TODO:
# 1. highlight selected section similar to tabbed sections
# 2. small caps / breadcrumb styling for headings
site_name: Glean Documentation
theme:
  name: material
  palette:
    scheme: glean
  logo: assets/glean-logo-white.png
  favicon: assets/favicon.svg
  custom_dir: overrides
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.tabs
extra:
  analytics:
    provider: segment
    api_key: !ENV SEGMENT_KEY
  generator: false
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - footnotes
extra_css:
  - assets/stylesheets/extra.css
nav:
  - Docs:
      - Glean:
          - Overview: index.md
      - Data Models:
          - Overview: docs/data-modeling/Data-Models-Overview.md
          - Add a Data Model: docs/data-modeling/add-data-model.md
          - Caching: docs/data-modeling/Caching.md
          - Data Modeling Best Practices: guides/data-modeling-best-practices.md
          - Calculating Metrics: docs/data-modeling/Metrics.md
      - Data Explorer:
          - docs/visualizing-data/Attributes-Tray.md
          - docs/visualizing-data/Breakout.md
          - docs/visualizing-data/Calculations.md
          - docs/visualizing-data/Chart-Interactions.md
          - docs/visualizing-data/Chart-Menu.md
          - docs/visualizing-data/Filter.md
          - docs/visualizing-data/Explorations.md
      - Dashboards:
          - docs/dashboards/Overview.md
          - docs/dashboards/Saved-Views.md
          - docs/dashboards/Metrics.md
          - docs/dashboards/Text.md
          - docs/dashboards/Filters.md
      - DataOps:
          - Overview: docs/data-ops/index.md
          - docs/data-ops/Creating-Data-Ops-Builds.md
          - docs/data-ops/Using-the-Glean-CLI.md
          - docs/data-ops/GRNs.md
          - Configuration Schemas:
              - docs/data-ops/config-schema/Data-Model.md
              - docs/data-ops/config-schema/Saved-View.md
              - docs/data-ops/config-schema/Dashboard.md
              - ./docs/data-ops/config-schema/Color-Palette.md
      - Guides:
          - Create Retention Curves: guides/create-retention-curves/index.md
      - Project Management:
          - Custom Styles: ./docs/project-management/custom-styles.md
          - Add a Data Warehouse: ./docs/project-management/database-connections.md
          - Data Warehouses:
              - ./docs/project-management/database-connections/snowflake.md
              - ./docs/project-management/database-connections/bigquery.md
              - ./docs/project-management/database-connections/redshift.md
              - ./docs/project-management/database-connections/mysql.md
              - ./docs/project-management/database-connections/athena.md
          - Organize Content with Collections: docs/project-management/collections.md
          - Project Invite Links: docs/project-management/invite-links.md
          - Get Access Domains: docs/project-management/get-access-domains.md
          - Users and Permissions: docs/project-management/users-and-permissions.md
      - Support:
          - Get in Touch: contact-us.md
  - Quickstart: guides/quickstart/index.md
  - Product Roadmap: ./product-roadmap/product-roadmap.md
  - Changelog:
      - Changelog:
          - ./changelog/2022_12_27.md
          - ./changelog/2022_11_21.md
          - ./changelog/2022_10_17.md
          - ./changelog/2022_09_19.md
          - ./changelog/2022_08_04.md
          - ./changelog/2022_06_20.md
