# TODO:
# 1. highlight selected section similar to tabbed sections 
# 2. small caps / breadcrumb styling for headings
site_name: Glean Documentation
theme:
  name: material
  palette:
    scheme: glean
  logo: assets/glean-logo-white.png
  favicon: assets/glean-logo.png
  custom_dir: overrides
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.tabs
extra:
  analytics:
    provider: segment
    property: 'YOUR_SEGMENT_KEY'
    api_key: !ENV SEGMENT_KEY
  generator: false
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - footnotes
extra_css:
  - assets/stylesheets/extra.css
nav:
    - Docs:
      - Glean:
        - Overview: index.md
      - Data Explorer:
        - docs/visualizing-data/Attributes-Tray.md
        - docs/visualizing-data/Breakout.md
        - docs/visualizing-data/Calculations.md
        - docs/visualizing-data/Chart-Interactions.md
        - docs/visualizing-data/Chart-Menu.md
        - docs/visualizing-data/Dashboards.md
        - docs/visualizing-data/Filter.md
      - Data Models:
        - Overview: docs/data-modeling/Data-Models-Overview.md
        - Add a Data Model: docs/data-modeling/add-data-model.md
        - Calculating Metrics: docs/data-modeling/Metrics.md
      - Data Ops:
        - Overview: docs/data-ops/index.md
        - docs/data-ops/Creating-Data-Ops-Builds.md
        - docs/data-ops/Using-the-Glean-CLI.md
        - docs/data-ops/DataOps-Configuration-Schema.md
      - People:
        - Users and Permissions: docs/users-and-permissions.md
      - Settings: 
        - Database Connections: docs/database-connections.md
      - Support:
        - Get in Touch: contact-us.md
      - Guides:
        - Create retention curves: guides/create-retention-curves/index.md
        - Data Modeling Best Practices: guides/data-modeling-best-practices.md
    - Quickstart: guides/quickstart/index.md