[tool.poetry]
name = "documentation"
version = "0.1.0"
description = ""
authors = ["Andrew Lee <hello@vndrewlee.com>"]

[tool.poetry.dependencies]
python = "^3.9"
mkdocs-material = "^8.2.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
